// Access + search over the local dataset (generated by scripts/build-data.mjs).
//
// The JSON ships in a compact form — see pokemonCodec for why and for the field
// map. It is decoded once here at import, so every consumer below (and every
// component) sees the same full objects it always did.
import { decodeAll, titleCase } from "./pokemonCodec";
import ROWS from "../data/pokemon.json";

const DATA = decodeAll(ROWS);

export const ALL_POKEMON = DATA;

const normalize = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

// Pixel sprite for search rows; falls back to artwork for the ~3 entries that
// have no pixel sprite (pikachu-starter, eevee-starter, zygarde-mega).
export const spriteFor = (p) => p.spriteUrl ?? p.artworkUrl;
export const artworkFor = (p) => p.artworkUrl ?? p.spriteUrl;

export const getBySlug = (slug) => DATA.find((p) => p.slug === slug);

// The selectable forms of a Pokémon (Base + Megas/regionals/battle forms),
// resolved from its `forms` slug list. Base (default) first.
export function formsOf(pokemon) {
  return pokemon.forms
    .map(getBySlug)
    .filter(Boolean)
    .sort((a, b) => (b.isDefault ? 1 : 0) - (a.isDefault ? 1 : 0));
}

// Short chip label for a form: "Base" for the default, else the suffix after
// the species name (e.g. "charizard-mega-x" → "Mega X").
export function formLabel(form) {
  if (form.isDefault) return "Base";
  const prefix = form.speciesSlug + "-";
  const rest = form.slug.startsWith(prefix)
    ? form.slug.slice(prefix.length)
    : form.slug;
  return titleCase(rest);
}

// Lightweight search-as-you-type: prefix matches rank above substring matches.
export function searchPokemon(query, limit = 8) {
  const q = normalize(query);
  if (!q) return [];
  const prefix = [];
  const contains = [];
  for (const p of DATA) {
    const name = normalize(p.name);
    const slug = normalize(p.slug);
    if (name.startsWith(q) || slug.startsWith(q)) prefix.push(p);
    else if (name.includes(q) || slug.includes(q)) contains.push(p);
  }
  return [...prefix, ...contains].slice(0, limit);
}
